version: '3.9'

networks:
  default:
    driver: bridge

# volumes:
#   add-volumes-here:
#     driver: local

services:
  php:
    build: 
      context: docker/php
      dockerfile: Dockerfile
    container_name: starter-php
    hostname: starter-php
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:80"
